services:
  
  spamassassin-app:
    image: tiredofit/spamassassin
    container_name: spamassassin-app
    ports: 
      - 783:783
    volumes:
      - ./logs/spamassassin:/logs
      - ./conf:/config
      - ./data:/data
    environment:
      - TIMEZONE=America/Vancouver
      - CONTAINER_NAME=spamassassin-app
    networks:
      - services
    restart: always

networks:
  services:
    external: true

