version: '3.7'
services:
  
  spamassassin-app:
    image: tiredofit/spamassassin
    container_name: spamassassin-app
    ports: 
    - 783:783
    volumes:
    - ./logs/spamassassin:/logs
    - ./conf:/config
    - ./data:/data
    environment:
    - CONTAINER_NAME=spamassassin-app
    networks:
    - internal
    - services
    restart: always

networks:
  internal:
    external: false
  services:
    external: true


